version: '3.7'
services:
  algorithm-api:
    image: untadee/algorithm-api:latest
    build: .
    ports:
      - "5000:5000"
    networks:
      - traefik-public
    deploy:
      # service resource management
      # resources:
      # service restart policy
      # replicas: 4
      # update_config:
      #   parallelism: 2
      #   order: start-first
      #   failure_action: rollback
      #   delay: 10s
      # rollback_config:
      #   parallelism: 0
      #   order: stop-first
      # restart_policy:
      #   condition: on-failure
      #   delay: 5s
      #   max_attempts: 3
      #   window: 120s
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.algorithm-api.rule=Host(`rais.dista.uninsubria.it`) && PathPrefix(`/algorithm`)
        - traefik.http.routers.algorithm-api.entrypoints=https
        - traefik.http.routers.algorithm-api.tls=true
networks:
  traefik-public:
    external: true